apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: baolamtranpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: baolamtranpipelinesjavascriptdocker 
    spec:
      containers:
        - name: baolamtranpipelinesjavascriptdocker 
          image: vinaoneacr.azurecr.io/baolamtranpipelinesjavascriptdocker
          ports:
          - containerPort: 8080